// ============================================================================
// DRUG INVENTORY & SUPPLY CHAIN TRACKING SYSTEM (PSS04)
// High-Fidelity Mock Data Engine & Initial State
// ============================================================================

import type {
  Drug,
  Batch,
  Hospital,
  Warehouse,
  Vendor,
  InventoryItem,
  PurchaseOrder,
  Shipment,
  ConsumptionRecord,
  ReplenishmentRequest,
  Alert,
  AuditLog,
  BlockchainRecord,
  AIRecommendation,
  User,
} from '../types';

// ─── Default Users for All 6 Roles ──────────────────────────────────────────

export const MOCK_USERS: Record<string, User> = {
  admin: {
    id: 'USR-001',
    name: 'Dr. Rajesh Verma',
    email: 'admin@mohfw.gov.in',
    role: 'admin',
    roleTitle: 'Director General — Central Supply Authority',
    associated_entity_id: 'CENTRAL-HQ',
    associated_entity_type: 'central',
    is_active: true,
  },
  procurement_officer: {
    id: 'USR-002',
    name: 'Suresh Menon',
    email: 'procurement@mohfw.gov.in',
    role: 'procurement_officer',
    roleTitle: 'Chief Procurement Officer',
    associated_entity_id: 'CENTRAL-PROC',
    associated_entity_type: 'central',
    is_active: true,
  },
  warehouse_manager: {
    id: 'USR-003',
    name: 'Vikram Sethi',
    email: 'vikram.sethi@warehouse-north.in',
    role: 'warehouse_manager',
    roleTitle: 'Superintendent — Central Medical Warehouse North',
    associated_entity_id: 'WH-001',
    associated_entity_type: 'warehouse',
    is_active: true,
  },
  hospital_staff: {
    id: 'USR-004',
    name: 'Dr. Ananya Sharma',
    email: 'ananya.sharma@aiims.edu',
    role: 'hospital_staff',
    roleTitle: 'Head of Pharmacy — AIIMS New Delhi',
    associated_entity_id: 'HOSP-001',
    associated_entity_type: 'hospital',
    is_active: true,
  },
  vendor: {
    id: 'USR-005',
    name: 'Arunav Patel',
    email: 'logistics@sunpharma.com',
    role: 'vendor',
    roleTitle: 'Supply Operations Lead — Sun Pharma Logistics',
    associated_entity_id: 'VEND-001',
    associated_entity_type: 'vendor',
    is_active: true,
  },
  compliance_officer: {
    id: 'USR-006',
    name: 'Pooja Kulkarni',
    email: 'quality@cdsco.gov.in',
    role: 'compliance_officer',
    roleTitle: 'Quality & Regulatory Inspector — CDSCO',
    associated_entity_id: 'CENTRAL-CDSCO',
    associated_entity_type: 'central',
    is_active: true,
  },
};

// ─── Master Drugs ───────────────────────────────────────────────────────────

export const MOCK_DRUGS: Drug[] = [
  {
    _id: 'd1',
    drug_id: 'DRUG-001',
    name: 'Human Insulin Regular (100 IU/ml)',
    generic_name: 'Regular Human Insulin Injection',
    category: 'Endocrinology / Critical Care',
    unit: 'vials',
    is_critical: true,
    min_safety_stock: 500,
    storage_temperature: 'cold_chain_2_8',
    therapeutic_class: 'Antidiabetic Hormone',
    dosage_form: 'Injectable Solution',
    strength: '100 IU/ml, 10ml',
    description: 'Fast-acting recombinant DNA human insulin. Requires continuous 2°C to 8°C cold chain.',
  },
  {
    _id: 'd2',
    drug_id: 'DRUG-002',
    name: 'Propofol 1% Injectable Emulsion',
    generic_name: 'Propofol Injection',
    category: 'Anesthetics / ICU',
    unit: 'ampoules',
    is_critical: true,
    min_safety_stock: 350,
    storage_temperature: 'ambient',
    therapeutic_class: 'General Anesthetic',
    dosage_form: 'IV Emulsion',
    strength: '10 mg/ml, 20ml',
    description: 'Short-acting intravenous sedative-hypnotic agent for induction and maintenance of anesthesia in ICU.',
  },
  {
    _id: 'd3',
    drug_id: 'DRUG-003',
    name: 'Ceftriaxone 1g Injection',
    generic_name: 'Ceftriaxone Sodium',
    category: 'Antibiotics / Emergency',
    unit: 'vials',
    is_critical: true,
    min_safety_stock: 800,
    storage_temperature: 'ambient',
    therapeutic_class: 'Third-Generation Cephalosporin',
    dosage_form: 'Powder for Injection',
    strength: '1 g',
    description: 'Broad-spectrum antibiotic used for bacterial meningitis, sepsis, and severe respiratory infections.',
  },
  {
    _id: 'd4',
    drug_id: 'DRUG-004',
    name: 'Remdesivir 100mg IV Lyophilized',
    generic_name: 'Remdesivir for Injection',
    category: 'Antivirals / Pandemic Reserve',
    unit: 'vials',
    is_critical: true,
    min_safety_stock: 300,
    storage_temperature: 'ambient',
    therapeutic_class: 'Nucleotide Analog Antiviral',
    dosage_form: 'Lyophilized Powder',
    strength: '100 mg',
    description: 'Antiviral indicated for acute severe viral pneumonia and emergency respiratory ward admissions.',
  },
  {
    _id: 'd5',
    drug_id: 'DRUG-005',
    name: 'Meropenem 1g IV Infusion',
    generic_name: 'Meropenem Trihydrate',
    category: 'Reserve Antibiotics',
    unit: 'vials',
    is_critical: true,
    min_safety_stock: 400,
    storage_temperature: 'ambient',
    therapeutic_class: 'Carbapenem Antibiotic',
    dosage_form: 'Powder for Solution',
    strength: '1000 mg',
    description: 'Reserve carbapenem antibiotic for multidrug-resistant hospital-acquired infections.',
  },
  {
    _id: 'd6',
    drug_id: 'DRUG-006',
    name: 'Paracetamol 1000mg/100ml IV Infusion',
    generic_name: 'Acetaminophen IV',
    category: 'Analgesics / General Ward',
    unit: 'bottles',
    is_critical: false,
    min_safety_stock: 1200,
    storage_temperature: 'ambient',
    therapeutic_class: 'Non-Opioid Analgesic & Antipyretic',
    dosage_form: 'IV Infusion Bottle',
    strength: '10 mg/ml, 100ml',
    description: 'First-line intravenous management of acute fever and peri-operative pain.',
  },
  {
    _id: 'd7',
    drug_id: 'DRUG-007',
    name: 'Atracurium Besylate 25mg/2.5ml',
    generic_name: 'Atracurium Besylate',
    category: 'Anesthetics / OT & ICU',
    unit: 'ampoules',
    is_critical: true,
    min_safety_stock: 250,
    storage_temperature: 'cold_chain_2_8',
    therapeutic_class: 'Neuromuscular Blocker',
    dosage_form: 'Injectable Solution',
    strength: '10 mg/ml, 2.5ml',
    description: 'Skeletal muscle relaxant during surgical procedures and mechanical ventilation.',
  },
  {
    _id: 'd8',
    drug_id: 'DRUG-008',
    name: 'Enoxaparin Sodium 40mg/0.4ml PFS',
    generic_name: 'Low Molecular Weight Heparin',
    category: 'Cardiovascular / Anticoagulants',
    unit: 'syringes',
    is_critical: true,
    min_safety_stock: 450,
    storage_temperature: 'ambient',
    therapeutic_class: 'Anticoagulant',
    dosage_form: 'Pre-filled Syringe',
    strength: '4000 IU (40mg) / 0.4ml',
    description: 'Prophylaxis and treatment of deep vein thrombosis (DVT) and pulmonary embolism in post-op wards.',
  },
];

// ─── Hospitals ──────────────────────────────────────────────────────────────

export const MOCK_HOSPITALS: Hospital[] = [
  {
    _id: 'h1',
    hospital_id: 'HOSP-001',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    tier: 'Tier-1',
    location_zone: 'Zone-North (Delhi NCR)',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi - 110029',
    contact_person: 'Dr. Ananya Sharma',
    contact_phone: '+91 11 2658 8500',
    contact_email: 'pharmacy@aiims.edu',
    bed_capacity: 2500,
    icu_beds: 350,
  },
  {
    _id: 'h2',
    hospital_id: 'HOSP-002',
    name: 'Safdarjung Hospital & Vardhman Mahavir Medical College',
    tier: 'Tier-1',
    location_zone: 'Zone-North (Delhi NCR)',
    address: 'Ring Road, Opposite AIIMS, New Delhi - 110029',
    contact_person: 'Dr. Mukul Anand',
    contact_phone: '+91 11 2616 5060',
    contact_email: 'stores@safdarjung.gov.in',
    bed_capacity: 1800,
    icu_beds: 220,
  },
  {
    _id: 'h3',
    hospital_id: 'HOSP-003',
    name: 'King George’s Medical University (KGMU)',
    tier: 'Tier-1',
    location_zone: 'Zone-North (Lucknow)',
    address: 'Shah Mina Rd, Chowk, Lucknow, Uttar Pradesh - 226003',
    contact_person: 'Dr. R. K. Srivastava',
    contact_phone: '+91 522 225 7450',
    contact_email: 'medstore@kgmu.org',
    bed_capacity: 4500,
    icu_beds: 400,
  },
  {
    _id: 'h4',
    hospital_id: 'HOSP-004',
    name: 'District Civil Hospital Ambala',
    tier: 'Tier-2',
    location_zone: 'Zone-North (Haryana)',
    address: 'Model Town, Ambala City, Haryana - 134003',
    contact_person: 'Dr. Geeta Saini',
    contact_phone: '+91 171 253 1120',
    contact_email: 'civilhospital.ambala@haryana.gov.in',
    bed_capacity: 400,
    icu_beds: 40,
  },
];

// ─── Central & Regional Warehouses ──────────────────────────────────────────

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    _id: 'w1',
    warehouse_id: 'WH-001',
    name: 'Central Medical Services Society (CMSS) North Hub',
    location_zone: 'Zone-North (Delhi NCR)',
    capacity: 250000,
    used_capacity: 172000,
    address: 'Sector 18, Industrial Area, Gurugram, Haryana - 122015',
    manager_user_id: 'USR-003',
    cold_storage_available: true,
  },
  {
    _id: 'w2',
    warehouse_id: 'WH-002',
    name: 'State Central Drug Depot Lucknow',
    location_zone: 'Zone-North (Lucknow)',
    capacity: 150000,
    used_capacity: 94000,
    address: 'Transport Nagar, Phase 2, Lucknow, Uttar Pradesh - 226012',
    manager_user_id: 'USR-007',
    cold_storage_available: true,
  },
  {
    _id: 'w3',
    warehouse_id: 'WH-003',
    name: 'Regional Health Logistics Hub Chandigarh',
    location_zone: 'Zone-North (Chandigarh)',
    capacity: 120000,
    used_capacity: 68000,
    address: 'Industrial Area Phase 1, Chandigarh - 160002',
    manager_user_id: 'USR-008',
    cold_storage_available: true,
  },
];

// ─── Certified Vendors / Suppliers ──────────────────────────────────────────

export const MOCK_VENDORS: Vendor[] = [
  {
    _id: 'v1',
    vendor_id: 'VEND-001',
    name: 'Sun Pharmaceutical Industries Ltd.',
    avg_lead_time_days: 4.2,
    reliability_score: 96,
    contact_email: 'govt.supplies@sunpharma.com',
    contact_phone: '+91 22 4324 4324',
    address: 'Sun House, CTS No. 201 B/1, Goregaon (E), Mumbai - 400063',
    is_active: true,
    active_orders_count: 3,
    compliance_certified: true,
  },
  {
    _id: 'v2',
    vendor_id: 'VEND-002',
    name: 'Cipla Ltd. Institutional Healthcare Division',
    avg_lead_time_days: 3.8,
    reliability_score: 98,
    contact_email: 'institutional@cipla.com',
    contact_phone: '+91 22 2482 6000',
    address: 'Cipla House, Peninsula Business Park, Lower Parel, Mumbai - 400013',
    is_active: true,
    active_orders_count: 2,
    compliance_certified: true,
  },
  {
    _id: 'v3',
    vendor_id: 'VEND-003',
    name: 'Biocon Biologics Ltd. (Cold Chain Specialized)',
    avg_lead_time_days: 5.5,
    reliability_score: 94,
    contact_email: 'biologics.orders@biocon.com',
    contact_phone: '+91 80 2808 2808',
    address: 'Biocon Park, Plot No. 2 & 3, Bommasandra IV Phase, Bengaluru - 560099',
    is_active: true,
    active_orders_count: 2,
    compliance_certified: true,
  },
  {
    _id: 'v4',
    vendor_id: 'VEND-004',
    name: 'Dr. Reddy’s Laboratories Ltd.',
    avg_lead_time_days: 4.9,
    reliability_score: 91,
    contact_email: 'supplychain@drreddys.com',
    contact_phone: '+91 40 4900 2900',
    address: '8-2-337, Road No. 3, Banjara Hills, Hyderabad - 500034',
    is_active: true,
    active_orders_count: 1,
    compliance_certified: true,
  },
];

// ─── Batches ────────────────────────────────────────────────────────────────

export const MOCK_BATCHES: Batch[] = [
  {
    _id: 'b1',
    batch_id: 'BATCH-INS-2026-081',
    drug_id: MOCK_DRUGS[0],
    location_id: 'WH-001',
    location_type: 'warehouse',
    manufacturer: 'Biocon Biologics Ltd.',
    quantity: 3200,
    manufacturing_date: '2026-01-10',
    expiry_date: '2027-01-09',
    quality_status: 'passed',
    inspection_notes: 'Cold chain integrity verified during receiving inspection (4.1°C average).',
  },
  {
    _id: 'b2',
    batch_id: 'BATCH-INS-2025-904',
    drug_id: MOCK_DRUGS[0],
    location_id: 'HOSP-001',
    location_type: 'hospital',
    manufacturer: 'Biocon Biologics Ltd.',
    quantity: 140,
    manufacturing_date: '2025-09-01',
    expiry_date: '2026-09-15',
    quality_status: 'passed',
    inspection_notes: 'Batch expiring in 30 days. Priority dispensing protocol active.',
  },
  {
    _id: 'b3',
    batch_id: 'BATCH-PRO-2026-112',
    drug_id: MOCK_DRUGS[1],
    location_id: 'HOSP-001',
    location_type: 'hospital',
    manufacturer: 'Sun Pharmaceutical Industries Ltd.',
    quantity: 85,
    manufacturing_date: '2026-02-15',
    expiry_date: '2027-08-14',
    quality_status: 'passed',
  },
  {
    _id: 'b4',
    batch_id: 'BATCH-PRO-2026-108',
    drug_id: MOCK_DRUGS[1],
    location_id: 'HOSP-002',
    location_type: 'hospital',
    manufacturer: 'Sun Pharmaceutical Industries Ltd.',
    quantity: 650,
    manufacturing_date: '2026-02-10',
    expiry_date: '2027-08-09',
    quality_status: 'passed',
  },
  {
    _id: 'b5',
    batch_id: 'BATCH-CEF-2026-401',
    drug_id: MOCK_DRUGS[2],
    location_id: 'WH-001',
    location_type: 'warehouse',
    manufacturer: 'Cipla Ltd.',
    quantity: 8500,
    manufacturing_date: '2026-03-01',
    expiry_date: '2028-02-28',
    quality_status: 'passed',
  },
  {
    _id: 'b6',
    batch_id: 'BATCH-REM-2026-019',
    drug_id: MOCK_DRUGS[3],
    location_id: 'WH-001',
    location_type: 'warehouse',
    manufacturer: 'Cipla Ltd.',
    quantity: 1200,
    manufacturing_date: '2026-01-20',
    expiry_date: '2027-07-19',
    quality_status: 'quarantine',
    inspection_notes: 'Temperature excursion detected during secondary transit (+18.4°C for 3h). QA pending.',
  },
];

// ─── Inventory ───────────────────────────────────────────────────────────────

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    _id: 'inv1',
    location_id: 'HOSP-001',
    location_type: 'hospital',
    drug_id: MOCK_DRUGS[0],
    available_stock: 140,
    reserved_stock: 40,
    incoming_stock: 400,
    expired_stock: 0,
    last_updated: '2026-08-16T08:30:00Z',
    reorder_level: 500,
  },
  {
    _id: 'inv2',
    location_id: 'HOSP-001',
    location_type: 'hospital',
    drug_id: MOCK_DRUGS[1],
    available_stock: 85,
    reserved_stock: 30,
    incoming_stock: 0,
    expired_stock: 0,
    last_updated: '2026-08-16T09:15:00Z',
    reorder_level: 350,
  },
  {
    _id: 'inv3',
    location_id: 'HOSP-001',
    location_type: 'hospital',
    drug_id: MOCK_DRUGS[2],
    available_stock: 1420,
    reserved_stock: 200,
    incoming_stock: 500,
    expired_stock: 0,
    last_updated: '2026-08-15T18:00:00Z',
    reorder_level: 800,
  },
  {
    _id: 'inv4',
    location_id: 'HOSP-002',
    location_type: 'hospital',
    drug_id: MOCK_DRUGS[1],
    available_stock: 650,
    reserved_stock: 50,
    incoming_stock: 0,
    expired_stock: 0,
    last_updated: '2026-08-16T07:45:00Z',
    reorder_level: 250,
  },
  {
    _id: 'inv5',
    location_id: 'WH-001',
    location_type: 'warehouse',
    drug_id: MOCK_DRUGS[0],
    available_stock: 3200,
    reserved_stock: 600,
    incoming_stock: 2000,
    expired_stock: 0,
    last_updated: '2026-08-16T10:00:00Z',
    reorder_level: 2000,
  },
  {
    _id: 'inv6',
    location_id: 'WH-001',
    location_type: 'warehouse',
    drug_id: MOCK_DRUGS[2],
    available_stock: 8500,
    reserved_stock: 1500,
    incoming_stock: 5000,
    expired_stock: 0,
    last_updated: '2026-08-16T10:30:00Z',
    reorder_level: 4000,
  },
];

// ─── Purchase Orders ─────────────────────────────────────────────────────────

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    _id: 'po1',
    order_id: 'PO-2026-0891',
    vendor_id: MOCK_VENDORS[0],
    drug_id: MOCK_DRUGS[1],
    quantity: 1200,
    unit_price: 185.5,
    total_amount: 222600,
    destination_location_id: 'WH-001',
    destination_location_type: 'warehouse',
    expected_delivery: '2026-08-20',
    status: 'approved',
    created_by: MOCK_USERS.procurement_officer,
    notes: 'Emergency replenishment for ICU Propofol demand surge across Zone-North institutions.',
    blockchain_tx_hash: '0x7e81fa2914c99b80b2a9e71d4d12c85b190f0a21cf8973b06381ab1947e45ef9',
    createdAt: '2026-08-15T11:20:00Z',
  },
  {
    _id: 'po2',
    order_id: 'PO-2026-0888',
    vendor_id: MOCK_VENDORS[2],
    drug_id: MOCK_DRUGS[0],
    quantity: 2500,
    unit_price: 240.0,
    total_amount: 600000,
    destination_location_id: 'WH-001',
    destination_location_type: 'warehouse',
    expected_delivery: '2026-08-18',
    status: 'shipped',
    created_by: MOCK_USERS.procurement_officer,
    notes: 'Cold chain certified batch under National Diabetes Control Programme.',
    blockchain_tx_hash: '0x4a92c90f23d114bc5678dae019b78292c10b45ff990172e811acb98124976c12',
    createdAt: '2026-08-12T14:45:00Z',
  },
  {
    _id: 'po3',
    order_id: 'PO-2026-0879',
    vendor_id: MOCK_VENDORS[1],
    drug_id: MOCK_DRUGS[2],
    quantity: 5000,
    unit_price: 62.0,
    total_amount: 310000,
    destination_location_id: 'WH-001',
    destination_location_type: 'warehouse',
    expected_delivery: '2026-08-14',
    actual_delivery: '2026-08-14T16:30:00Z',
    status: 'delivered',
    created_by: MOCK_USERS.procurement_officer,
    notes: 'Fulfilled on schedule. Batch quality passed inspection.',
    blockchain_tx_hash: '0x19a8bc43d7e821109ff621bca9082346ef870a41bc9891024317865e908712bc',
    createdAt: '2026-08-08T09:00:00Z',
  },
  {
    _id: 'po4',
    order_id: 'PO-2026-0895',
    vendor_id: MOCK_VENDORS[3],
    drug_id: MOCK_DRUGS[4],
    quantity: 800,
    unit_price: 450.0,
    total_amount: 360000,
    destination_location_id: 'HOSP-001',
    destination_location_type: 'hospital',
    expected_delivery: '2026-08-25',
    status: 'pending',
    created_by: MOCK_USERS.procurement_officer,
    notes: 'Direct hospital replenishment requisition pending financial sanction.',
    createdAt: '2026-08-16T09:30:00Z',
  },
];

// ─── Shipments ───────────────────────────────────────────────────────────────

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    _id: 's1',
    shipment_id: 'SHP-2026-0412',
    order_id: MOCK_PURCHASE_ORDERS[1],
    origin_id: 'VEND-003 (Biocon Bengaluru)',
    origin_type: 'vendor',
    destination_id: 'WH-001 (CMSS North Hub Gurugram)',
    destination_type: 'warehouse',
    drug_id: MOCK_DRUGS[0],
    quantity: 2500,
    status: 'in_transit',
    estimated_arrival: '2026-08-18T18:00:00Z',
    carrier_name: 'BlueDart ColdChain Express (Reefer Truck HR-55-AJ-9021)',
    tracking_number: 'BD-CC-9018471',
    tracking_note: 'En route via NH-44 near Gwalior Bypass. Active IoT temperature: +4.3°C.',
    temperature_log: [4.1, 4.3, 4.2, 4.5, 4.3, 4.4, 4.2],
    milestones: [
      {
        stage: 'Dispatched from Biocon Bengaluru Facility',
        location: 'Bengaluru, Karnataka',
        timestamp: '2026-08-14T08:00:00Z',
        status: 'completed',
        temperature: 3.9,
      },
      {
        stage: 'Nagpur Central Transit Hub Verification',
        location: 'Nagpur, Maharashtra',
        timestamp: '2026-08-15T19:30:00Z',
        status: 'completed',
        temperature: 4.2,
      },
      {
        stage: 'In-Transit to Delhi NCR Corridor',
        location: 'Gwalior Bypass, Madhya Pradesh',
        timestamp: '2026-08-16T11:00:00Z',
        status: 'current',
        temperature: 4.3,
      },
      {
        stage: 'Final Receiving & Dock Inspection at WH-001',
        location: 'Gurugram, Haryana',
        timestamp: '2026-08-18T18:00:00Z',
        status: 'pending',
      },
    ],
    blockchain_tx_hash: '0x6b19ea8102431cf982a74e509172bc98341af87019234871e982341076bca912',
    createdAt: '2026-08-14T08:00:00Z',
  },
  {
    _id: 's2',
    shipment_id: 'SHP-2026-0418',
    order_id: 'TRANSFER-PROP-001',
    origin_id: 'HOSP-002 (Safdarjung Hospital)',
    origin_type: 'hospital',
    destination_id: 'HOSP-001 (AIIMS New Delhi)',
    destination_type: 'hospital',
    drug_id: MOCK_DRUGS[1],
    quantity: 200,
    status: 'preparing',
    estimated_arrival: '2026-08-16T15:30:00Z',
    carrier_name: 'AIIMS Dedicated Emergency Courier Van (DL-1T-4401)',
    tracking_number: 'AIIMS-EMG-0816',
    tracking_note: 'AI Coordinator Agent automated surplus redistribution dispatch.',
    milestones: [
      {
        stage: 'Redistribution Order Sanctioned by Central Authority',
        location: 'Central Command',
        timestamp: '2026-08-16T10:15:00Z',
        status: 'completed',
      },
      {
        stage: 'Packaging & Batch Segregation at Safdarjung Pharmacy',
        location: 'Safdarjung Hospital, New Delhi',
        timestamp: '2026-08-16T11:30:00Z',
        status: 'current',
      },
      {
        stage: 'Delivery & Immediate Ward Ingestion at AIIMS ICU',
        location: 'AIIMS New Delhi',
        timestamp: '2026-08-16T15:30:00Z',
        status: 'pending',
      },
    ],
    blockchain_tx_hash: '0x99238bc1a78e4119024fbc91024876e9871024bc109823471029834710298347',
    createdAt: '2026-08-16T10:15:00Z',
  },
  {
    _id: 's3',
    shipment_id: 'SHP-2026-0399',
    order_id: MOCK_PURCHASE_ORDERS[2],
    origin_id: 'VEND-001 (Sun Pharma)',
    origin_type: 'vendor',
    destination_id: 'WH-001 (CMSS North Hub)',
    destination_type: 'warehouse',
    drug_id: MOCK_DRUGS[2],
    quantity: 5000,
    status: 'delivered',
    estimated_arrival: '2026-08-14T15:00:00Z',
    actual_arrival: '2026-08-14T16:30:00Z',
    carrier_name: 'Safexpress Logistics',
    tracking_number: 'SFX-9018471',
    blockchain_tx_hash: '0x19a8bc43d7e821109ff621bca9082346ef870a41bc9891024317865e908712bc',
    createdAt: '2026-08-10T10:00:00Z',
  },
];

// ─── Hospital Consumption Records ───────────────────────────────────────────

export const MOCK_CONSUMPTION: ConsumptionRecord[] = [
  {
    _id: 'c1',
    hospital_id: 'HOSP-001',
    drug_id: MOCK_DRUGS[1],
    batch_id: 'BATCH-PRO-2026-112',
    period_start: '2026-08-15T00:00:00Z',
    period_end: '2026-08-15T23:59:59Z',
    quantity_consumed: 68,
    daily_avg_consumption: 68,
    is_anomaly: true,
    anomaly_reason: '209% spike above 14-day moving average due to emergency polytrauma admissions & neurosurgery ICU surge.',
    recorded_by: MOCK_USERS.hospital_staff,
    notes: 'Urgent notice dispatched to central procurement.',
    createdAt: '2026-08-16T06:30:00Z',
  },
  {
    _id: 'c2',
    hospital_id: 'HOSP-001',
    drug_id: MOCK_DRUGS[1],
    batch_id: 'BATCH-PRO-2026-112',
    period_start: '2026-08-14T00:00:00Z',
    period_end: '2026-08-14T23:59:59Z',
    quantity_consumed: 54,
    daily_avg_consumption: 54,
    is_anomaly: true,
    anomaly_reason: 'Unusual spike in ICU bed occupancy rate (98.4%).',
    recorded_by: MOCK_USERS.hospital_staff,
    createdAt: '2026-08-15T06:30:00Z',
  },
  {
    _id: 'c3',
    hospital_id: 'HOSP-001',
    drug_id: MOCK_DRUGS[1],
    batch_id: 'BATCH-PRO-2026-112',
    period_start: '2026-08-13T00:00:00Z',
    period_end: '2026-08-13T23:59:59Z',
    quantity_consumed: 26,
    daily_avg_consumption: 26,
    is_anomaly: false,
    recorded_by: MOCK_USERS.hospital_staff,
    createdAt: '2026-08-14T06:30:00Z',
  },
  {
    _id: 'c4',
    hospital_id: 'HOSP-001',
    drug_id: MOCK_DRUGS[0],
    batch_id: 'BATCH-INS-2025-904',
    period_start: '2026-08-15T00:00:00Z',
    period_end: '2026-08-15T23:59:59Z',
    quantity_consumed: 42,
    daily_avg_consumption: 42,
    is_anomaly: false,
    recorded_by: MOCK_USERS.hospital_staff,
    createdAt: '2026-08-16T06:45:00Z',
  },
  {
    _id: 'c5',
    hospital_id: 'HOSP-001',
    drug_id: MOCK_DRUGS[2],
    batch_id: 'BATCH-CEF-2026-401',
    period_start: '2026-08-15T00:00:00Z',
    period_end: '2026-08-15T23:59:59Z',
    quantity_consumed: 110,
    daily_avg_consumption: 110,
    is_anomaly: false,
    recorded_by: MOCK_USERS.hospital_staff,
    createdAt: '2026-08-16T07:00:00Z',
  },
];

// ─── Replenishment Requests ─────────────────────────────────────────────────

export const MOCK_REPLENISHMENTS: ReplenishmentRequest[] = [
  {
    _id: 'r1',
    request_id: 'REQ-2026-0104',
    hospital_id: 'HOSP-001',
    hospital_name: 'AIIMS New Delhi',
    drug_id: MOCK_DRUGS[1],
    requested_quantity: 300,
    approved_quantity: 200,
    urgency: 'critical',
    reason: 'Stockout projected within 32 hours due to severe ICU consumption surge.',
    status: 'dispatched',
    allocated_from: 'HOSP-002 (Safdarjung Surplus Transfer)',
    shipment_id: 'SHP-2026-0418',
    requested_by: 'Dr. Ananya Sharma',
    createdAt: '2026-08-16T09:00:00Z',
  },
  {
    _id: 'r2',
    request_id: 'REQ-2026-0102',
    hospital_id: 'HOSP-001',
    hospital_name: 'AIIMS New Delhi',
    drug_id: MOCK_DRUGS[0],
    requested_quantity: 500,
    approved_quantity: 400,
    urgency: 'urgent',
    reason: 'Existing batch near expiry (30 days remaining). Requesting fresh reserve stock.',
    status: 'allocated',
    allocated_from: 'WH-001 (CMSS North Hub)',
    requested_by: 'Dr. Ananya Sharma',
    createdAt: '2026-08-15T14:00:00Z',
  },
  {
    _id: 'r3',
    request_id: 'REQ-2026-0098',
    hospital_id: 'HOSP-004',
    hospital_name: 'District Civil Hospital Ambala',
    drug_id: MOCK_DRUGS[2],
    requested_quantity: 600,
    urgency: 'standard',
    status: 'pending',
    requested_by: 'Dr. Geeta Saini',
    createdAt: '2026-08-16T10:30:00Z',
  },
];

// ─── Alerts & Incidents ──────────────────────────────────────────────────────

export const MOCK_ALERTS: Alert[] = [
  {
    _id: 'a1',
    alert_id: 'ALT-2026-092',
    alert_type: 'critical_stock',
    severity: 'critical',
    drug_id: MOCK_DRUGS[1],
    location_id: 'HOSP-001',
    message: 'CRITICAL STOCKOUT RISK: Propofol 1% stock at AIIMS is 85 ampoules (Safety Threshold: 350). Estimated stockout in 31 hours.',
    is_resolved: false,
    createdAt: '2026-08-16T07:15:00Z',
  },
  {
    _id: 'a2',
    alert_id: 'ALT-2026-090',
    alert_type: 'unusual_consumption',
    severity: 'high',
    drug_id: MOCK_DRUGS[1],
    location_id: 'HOSP-001',
    message: 'ANOMALY DETECTED: Daily consumption of Propofol at AIIMS increased by 209% (68 vs 22 baseline avg).',
    is_resolved: false,
    createdAt: '2026-08-16T06:35:00Z',
  },
  {
    _id: 'a3',
    alert_id: 'ALT-2026-088',
    alert_type: 'expiring_drug',
    severity: 'medium',
    drug_id: MOCK_DRUGS[0],
    location_id: 'HOSP-001',
    message: 'EXPIRY WARNING: Batch BATCH-INS-2025-904 (140 vials) expires on 2026-09-15 (30 days remaining).',
    is_resolved: false,
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    _id: 'a4',
    alert_id: 'ALT-2026-085',
    alert_type: 'quality_issue',
    severity: 'high',
    drug_id: MOCK_DRUGS[3],
    location_id: 'WH-001',
    message: 'QUALITY QUARANTINE: Batch BATCH-REM-2026-019 placed in quarantine due to transit temperature excursion (+18.4°C).',
    is_resolved: false,
    createdAt: '2026-08-14T16:00:00Z',
  },
  {
    _id: 'a5',
    alert_id: 'ALT-2026-079',
    alert_type: 'low_stock',
    severity: 'medium',
    drug_id: MOCK_DRUGS[0],
    location_id: 'HOSP-001',
    message: 'LOW STOCK: Human Insulin at AIIMS is at 140 vials (Min safety: 500). Replenishment order PO-2026-0888 is in transit.',
    is_resolved: true,
    resolved_by: MOCK_USERS.admin,
    resolved_at: '2026-08-15T15:30:00Z',
    resolution_notes: 'Replenishment dispatched from Central Hub via cold-chain carrier.',
    createdAt: '2026-08-14T11:00:00Z',
  },
];

// ─── Multi-Agent AI Recommendation ──────────────────────────────────────────

export const MOCK_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    _id: 'ai-rec-1',
    recommendation_id: 'AI-REC-2026-0816-01',
    snapshot_id: 'SNAP-908124-DELHI-NCR',
    overall_risk_level: 'critical',
    agent_findings: [
      {
        agent_name: 'DemandAgent',
        finding_type: 'projected_stockout_surge',
        severity: 'critical',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1% Injectable Emulsion',
        target_location_id: 'HOSP-001 (AIIMS New Delhi)',
        description: 'AIIMS daily consumption surged from 22 units/day to 68 units/day (+209%). At current run rate, current available stock of 85 units will be exhausted in ~30 hours.',
        metrics: {
          baseline_daily_avg: 22,
          current_daily_consumption: 68,
          surge_percentage: '+209%',
          hours_to_stockout: 30.2,
          confidence_score: 0.96,
        },
      },
      {
        agent_name: 'InventoryAgent',
        finding_type: 'batch_stock_assessment',
        severity: 'high',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1%',
        target_location_id: 'HOSP-001',
        description: 'AIIMS has zero incoming purchase orders for Propofol. Central Warehouse WH-001 has low emergency reserve (120 units).',
        metrics: {
          current_stock: 85,
          min_safety_stock: 350,
          deficit: 265,
          warehouse_available: 120,
        },
      },
      {
        agent_name: 'DistributionAgent',
        finding_type: 'inter_hospital_surplus_match',
        severity: 'low',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1%',
        target_location_id: 'HOSP-002 (Safdarjung Hospital)',
        description: 'Identified surplus inventory of 650 units at Safdarjung Hospital (located 1.2 km from AIIMS). Safdarjung 14-day consumption requirement is only 220 units.',
        metrics: {
          surplus_location: 'HOSP-002',
          available_surplus: 350,
          distance_km: 1.2,
          transfer_time_hours: 1.5,
          recommended_transfer_qty: 200,
        },
      },
      {
        agent_name: 'ProcurementAgent',
        finding_type: 'bulk_reorder_recommendation',
        severity: 'medium',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1%',
        target_location_id: 'WH-001 (Central Hub)',
        description: 'Recommended expediting Purchase Order PO-2026-0891 (1,200 units) with Sun Pharma to replenish both Central Warehouse and Safdarjung surplus depletion.',
        metrics: {
          recommended_procure_qty: 1200,
          vendor: 'Sun Pharmaceutical Industries Ltd.',
          lead_time_days: 3.5,
          estimated_cost_inr: 222600,
        },
      },
      {
        agent_name: 'ComplianceAgent',
        finding_type: 'quality_shelf_life_validation',
        severity: 'low',
        target_drug_id: 'DRUG-002',
        target_location_id: 'HOSP-002',
        description: 'Safdarjung surplus batch (BATCH-PRO-2026-108) validated: Expiry August 2027 (12+ months shelf life remaining), Quality Status: PASSED.',
        metrics: {
          batch_id: 'BATCH-PRO-2026-108',
          expiry: '2027-08-09',
          quality: 'PASSED',
          regulatory_compliance: '100% OK',
        },
      },
      {
        agent_name: 'CoordinatorAgent',
        finding_type: 'synthesized_decision_matrix',
        severity: 'critical',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1%',
        description: 'OPTIMAL TWO-PRONGED SOLUTION SYNTHESIZED: (1) Immediate inter-hospital transfer of 200 units from Safdarjung to AIIMS resolves stockout within 4 hours; (2) Bulk purchase order of 1,200 units from Sun Pharma restores network safety buffer.',
        metrics: {
          prevented_stockouts: 1,
          time_saved_hours: 68,
          cost_efficiency: '94.2%',
          human_in_the_loop_required: true,
        },
      },
    ],
    recommended_actions: [
      {
        action_type: 'redistribute',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1% Injectable Emulsion',
        source_location_id: 'HOSP-002 (Safdarjung Hospital)',
        destination_location_id: 'HOSP-001 (AIIMS New Delhi)',
        recommended_quantity: 200,
        priority: 'critical',
        reasoning: 'Immediate inter-hospital transfer eliminates projected ICU stockout within 4 hours without compromising Safdarjung safety margins.',
        confidence: 0.98,
      },
      {
        action_type: 'procure',
        target_drug_id: 'DRUG-002',
        target_drug_name: 'Propofol 1% Injectable Emulsion',
        source_location_id: 'VEND-001 (Sun Pharma)',
        destination_location_id: 'WH-001 (CMSS Central Hub)',
        recommended_quantity: 1200,
        priority: 'high',
        reasoning: 'Replenishes central buffer and compensates for emergency inter-hospital transfer before regional stock depletion.',
        confidence: 0.92,
      },
    ],
    requires_human_approval: true,
    approval_status: 'pending',
    createdAt: '2026-08-16T10:00:00Z',
  },
];

// ─── Blockchain Immutable Audit Trail ───────────────────────────────────────

export const MOCK_BLOCKCHAIN_RECORDS: BlockchainRecord[] = [
  {
    tx_hash: '0x7e81fa2914c99b80b2a9e71d4d12c85b190f0a21cf8973b06381ab1947e45ef9',
    block_number: 19840212,
    timestamp: '2026-08-15T11:20:14Z',
    event_type: 'PO_CREATED',
    actor: 'Suresh Menon (CPO)',
    actor_role: 'Procurement Officer',
    entity_id: 'PO-2026-0891',
    entity_type: 'PurchaseOrder',
    payload_hash: 'sha256:4b91ac09e8712bc9018247fab901847109234871e982341076bca91290184712',
    gas_used: '84,210',
    is_verified: true,
    block_explorer_url: 'https://sepolia.etherscan.io/tx/0x7e81fa2914c99b80b2a9e71d4d12c85b190f0a21cf8973b06381ab1947e45ef9',
  },
  {
    tx_hash: '0x4a92c90f23d114bc5678dae019b78292c10b45ff990172e811acb98124976c12',
    block_number: 19839810,
    timestamp: '2026-08-14T08:00:22Z',
    event_type: 'SHIPMENT_DISPATCHED',
    actor: 'Arunav Patel',
    actor_role: 'Vendor Supplier',
    entity_id: 'SHP-2026-0412',
    entity_type: 'Shipment',
    payload_hash: 'sha256:19024fbc91024876e9871024bc10982347102983471029834710928347109283',
    gas_used: '96,400',
    is_verified: true,
    block_explorer_url: 'https://sepolia.etherscan.io/tx/0x4a92c90f23d114bc5678dae019b78292c10b45ff990172e811acb98124976c12',
  },
  {
    tx_hash: '0x19a8bc43d7e821109ff621bca9082346ef870a41bc9891024317865e908712bc',
    block_number: 19838902,
    timestamp: '2026-08-14T16:30:05Z',
    event_type: 'SHIPMENT_DELIVERED',
    actor: 'Vikram Sethi',
    actor_role: 'Warehouse Superintendent',
    entity_id: 'SHP-2026-0399',
    entity_type: 'Shipment',
    payload_hash: 'sha256:71982341076bca912901847124b91ac09e8712bc9018247fab90184710923487',
    gas_used: '112,050',
    is_verified: true,
    block_explorer_url: 'https://sepolia.etherscan.io/tx/0x19a8bc43d7e821109ff621bca9082346ef870a41bc9891024317865e908712bc',
  },
  {
    tx_hash: '0x99238bc1a78e4119024fbc91024876e9871024bc109823471029834710298347',
    block_number: 19840450,
    timestamp: '2026-08-16T10:15:42Z',
    event_type: 'STOCK_REDISTRIBUTED',
    actor: 'Dr. Rajesh Verma',
    actor_role: 'Admin / Central Authority',
    entity_id: 'TRANSFER-PROP-001',
    entity_type: 'ReplenishmentAllocation',
    payload_hash: 'sha256:9018247fab901847109234871e982341076bca912901847124b91ac09e8712bc9',
    gas_used: '105,800',
    is_verified: true,
    block_explorer_url: 'https://sepolia.etherscan.io/tx/0x99238bc1a78e4119024fbc91024876e9871024bc109823471029834710298347',
  },
];

// ─── Application Audit Trail ────────────────────────────────────────────────

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    _id: 'aud1',
    action: 'AI_RECOMMENDATION_TRIGGERED',
    performed_by: { name: 'Dr. Rajesh Verma', role: 'admin' },
    entity_type: 'AIRecommendation',
    entity_id: 'AI-REC-2026-0816-01',
    changes: {
      trigger: 'Manual analysis invocation for Zone-North operational snapshot',
      result: 'Critical risk detected (Propofol stockout)',
    },
    ip_address: '14.139.60.2 (Ministry Central Network)',
    blockchain_tx_hash: '0x99238bc1a78e4119024fbc91024876e9871024bc109823471029834710298347',
    is_blockchain_verified: true,
    createdAt: '2026-08-16T10:00:15Z',
  },
  {
    _id: 'aud2',
    action: 'CONSUMPTION_RECORDED',
    performed_by: { name: 'Dr. Ananya Sharma', role: 'hospital_staff' },
    entity_type: 'ConsumptionRecord',
    entity_id: 'c1',
    changes: {
      drug: 'Propofol 1% Injectable Emulsion',
      quantity_consumed: 68,
      is_anomaly: true,
    },
    ip_address: '14.139.57.10 (AIIMS Internal Intranet)',
    createdAt: '2026-08-16T06:30:00Z',
  },
  {
    _id: 'aud3',
    action: 'PURCHASE_ORDER_APPROVED',
    performed_by: { name: 'Suresh Menon', role: 'procurement_officer' },
    entity_type: 'PurchaseOrder',
    entity_id: 'PO-2026-0891',
    changes: {
      before: { status: 'pending' },
      after: { status: 'approved' },
    },
    ip_address: '14.139.60.18',
    blockchain_tx_hash: '0x7e81fa2914c99b80b2a9e71d4d12c85b190f0a21cf8973b06381ab1947e45ef9',
    is_blockchain_verified: true,
    createdAt: '2026-08-15T11:20:00Z',
  },
  {
    _id: 'aud4',
    action: 'BATCH_QUARANTINED',
    performed_by: { name: 'Pooja Kulkarni', role: 'compliance_officer' },
    entity_type: 'Batch',
    entity_id: 'BATCH-REM-2026-019',
    changes: {
      before: { quality_status: 'passed' },
      after: { quality_status: 'quarantine', reason: 'Transit temperature excursion' },
    },
    ip_address: '115.112.240.18 (CDSCO Regulatory Terminal)',
    is_blockchain_verified: true,
    createdAt: '2026-08-14T16:00:00Z',
  },
];
