from datetime import datetime
from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field

class AgentFindingSchema(BaseModel):
    """
    Individual finding generated by a specialized agent (e.g. DemandAgent, ComplianceAgent).
    """
    agent_name: str = Field(..., description="Name of analyzing agent e.g. DemandAgent")
    finding_type: str = Field(..., description="Category e.g. projected_stockout, batch_expiry_risk, vendor_delay")
    severity: Literal["low", "medium", "high", "critical"] = Field(..., description="Severity level")
    target_drug_id: str = Field(..., description="Drug ID affected")
    target_location_id: Optional[str] = Field(default=None, description="Hospital/Warehouse ID affected")
    description: str = Field(..., description="Clear natural-language narrative of the issue")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Supporting empirical data values")


class ActionRecommendationSchema(BaseModel):
    """
    Actionable decision recommendation produced by agents or Coordinator.
    """
    action_type: Literal["redistribute", "procure", "quarantine_batch", "expedite_shipment", "no_action"] = Field(
        ..., description="Recommended action type"
    )
    target_drug_id: str = Field(..., description="Drug ID target")
    source_location_id: Optional[str] = Field(default=None, description="Source hospital/warehouse ID (for transfer)")
    destination_location_id: str = Field(..., description="Destination hospital/warehouse ID requiring action")
    recommended_quantity: int = Field(..., ge=0, description="Recommended quantity for action")
    priority: Literal["low", "medium", "high", "critical"] = Field(..., description="Action priority")
    reasoning: str = Field(..., description="Explanation of why this action is recommended")
    confidence: float = Field(default=0.85, ge=0.0, le=1.0, description="Confidence score of AI recommendation")


class CoordinatorRecommendationResponse(BaseModel):
    """
    Master machine-readable recommendation payload generated by Coordinator Agent.
    Returned by FastAPI endpoint POST /api/v1/analyze.
    """
    recommendation_id: str = Field(..., description="Unique recommendation session ID")
    snapshot_id: str = Field(..., description="Reference snapshot ID analyzed")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of analysis completion")
    overall_risk_level: Literal["low", "medium", "high", "critical"] = Field(..., description="Highest overall risk detected")
    agent_findings: List[AgentFindingSchema] = Field(default_factory=list, description="Findings from specialized agents")
    recommended_actions: List[ActionRecommendationSchema] = Field(default_factory=list, description="Prioritized recommendations")
    requires_human_approval: bool = Field(default=True, description="Flag indicating human confirmation is required")
